import { Router } from "express";
import fhirOrganizationRoute from "./fhirOrganization.route";
import fhirAccessTokenRoute from "./fhirAccessToken.route";
import fhirPractitionerRoute from "./fhirPractitioner.route";
import fhirPatientRoute from "./fhirPatient.route";
import fhirLocationRoute from "./fhirLocation.route";
import fhirEncounterRoute from "./fhirEncounter.route";
import fhirObservationRoute from "./fhirObservation.route";
import fhirKycRoute from "./fhirKyc.route";
import fhirCarePlanRoute from "./fhirCarePlan.route";
import fhirProcedureRoute from "./fhirProcedure.route";
import fhirPrognosaRoute from "./fhirPrognosa.route";
import fhirAllergyRoute from "./fhirAllergy.route";
import fhirLaboratoryRoute from "./fhirLaboratory.route";
const fhirRoute = Router();

fhirRoute.use("/token", fhirAccessTokenRoute);
fhirRoute.use("/organization", fhirOrganizationRoute);
fhirRoute.use("/practitioner", fhirPractitionerRoute);
fhirRoute.use("/patient", fhirPatientRoute);
fhirRoute.use("/location", fhirLocationRoute);
fhirRoute.use("/encounter", fhirEncounterRoute);
fhirRoute.use("/observation", fhirObservationRoute);
fhirRoute.use("/kyc", fhirKycRoute);
fhirRoute.use("/careplan", fhirCarePlanRoute);
fhirRoute.use("/procedure", fhirProcedureRoute);
fhirRoute.use("/prognosa", fhirPrognosaRoute);
fhirRoute.use("/allergy", fhirAllergyRoute);
fhirRoute.use("/laboratory", fhirLaboratoryRoute);
export default fhirRoute;
